image: maven:latest

#include:
#  - template: Jobs/Code-Quality.gitlab-ci.yml
#  - template: Jobs/SAST.gitlab-ci.yml

stages:
  - build
  - test
  - release

before_script:
  - mkdir -p target

cache:
  paths:
    - target/

#check_formatting:
#  stage: build
#  image: maven:3-openjdk-11
#  script:
#    - mvn spotless:check

#build:
#  stage: build
#  script:
#    - mvn clean package
#    - mv version.xml target/version.xml
#  artifacts:
#    paths:
#      - target/*.jar
#      - target/version.xml
#      - target/lib/

#unit_tests:
#  stage: test
#  script:
#    - mvn test
#
#integration_tests:
#  stage: test
#  image:
#    name: apache/hop:latest
#    entrypoint: [ "" ]
#  script:
#    - mkdir -p /files
#    - mkdir -p /opt/hop/plugins/transforms/geometryfieldsconverter
#    - cp -r integration_test/* /files/
#    - cp -r target/* /opt/hop/plugins/transforms/geometryfieldsconverter/
#    - /opt/hop/hop-run.sh -r local -f /files/pipeline.hpl

speed_test:
  stage: test
  image:
    name: apache/hop:latest
    entrypoint: [ "" ]
  before_script:
    - /opt/hop/hop-conf.sh -pc -p speed_test -ph /files
    - wget https://github.com/atolcd/hop-gis-plugins/releases/download/v1.4.0/gis-plugin-assemblies-1.4.0.zip -O gis.zip
    - unzip gis.zip -d /opt/hop/plugins/
    - mkdir -p /files
    - mkdir -p /opt/hop/plugins/transforms/geometryfieldsconverter
    - cp -r speed_test/* /files/
    - cp -r target/* /opt/hop/plugins/transforms/geometryfieldsconverter/
  script:
    - /opt/hop/hop-run.sh -j speed_test -r local -f /files/speed_test.hpl
    - cp /files/metrics.json $CI_PROJECT_DIR/speed_test/metrics.json
  artifacts:
    paths:
      - speed_test/metrics.json

evaluate_performance:
  stage: test
  image: bash:latest
  dependencies:
    - speed_test
  script:
    - apt-get update && apt-get install -y jq
    - ls -la
    - ls -la speed_test
    - ls -la target
    - cat speed_test/metrics.json
    - bash speed_test/evaluate_performance.sh

prepare_release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - apt-get update && apt-get install -y zip
    - mvn -B package
    - VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    - ZIP_NAME="geometry-fields-converter-$VERSION.zip"
    - cd target
    - zip -r "../$ZIP_NAME" version.xml lib hop-transform-geometryfieldsconverter-$VERSION.jar
  artifacts:
    paths:
      - "*.zip"
    expire_in: never