image: maven:latest

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml

stages:
  - build
  - test

before_script:
  - mkdir -p target

cache:
  paths:
    - target/

build:
  stage: build
  script:
    - mvn clean package
    - mv version.xml target/version.xml
  artifacts:
    paths:
      - target/*.jar
      - target/version.xml
      - target/lib/

unit_tests:
  stage: test
  script:
    - mvn test

integration_tests:
  stage: test
  script:
    - docker run -v target:/opt/hop/plugins/transforms/wktwkbconverter
      -v integration_test:/files -it --rm
      --env HOP_LOG_LEVEL=Basic
      --env HOP_FILE_PATH=/files/pipeline.hpl
      --env HOP_PROJECT_FOLDER=/files
      --env HOP_PROJECT_NAME=integration_test
      --env HOP_RUN_CONFIG=local
      --name hop-test-container
      apache/hop:latest